name: Graph TDD

on:
  push:
    branches: [ '**' ]  # Triggers on push to any branch
  pull_request:
    branches: [ '**' ]  # Triggers on pull requests to any branch

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      # ✅ Set environment variable for Dev/Prod
      - name: Set environment mode
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Run Tests (Skip Acceptance Tests)
        run: |
          if [[ "$ENVIRONMENT" == "production" ]]; then
            pipenv run python3 -m pytest --verbose --cov=. --cov-report=xml --junitxml=junit.xml --base-url=https://build-graph-with-tdd-bc2becbeccff.herokuapp.com -m "not acceptance_test"
          else
            pipenv run python3 -m pytest --verbose --cov=. --cov-report=xml --junitxml=junit.xml --base-url=http://localhost:5001 -m "not acceptance_test"
          fi

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Deploy only on the main branch
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/build-graph-with-tdd-bc2becbeccff.git
          git push heroku main
